### ISSUE TITLE
Komplettera för G

### ISSUE THREAD

**Issue by 1dv449** [jb223cp/1dv449_jb223cp_lab3#1]
Komplettera din readme.md med följande:
- CSRF, vad är det?
- Skillnad hashning och kryptering. Samt hur man gör när man hashar lösenord. Lösenordshantering
- Web sockets

**Comment by Bejta** [comment]
Readme.md kompletterad.

**Comment by 1dv449** [comment]
Bra skrivet! Stänger denna och du är godkänd på alla laborationer
